export const guides = [
    "The Complete Guide to Full Stack Web3 Development ",
    "10 Must-Know Patterns for Writing Clean Code with React and TypeScript✨🛀 ",
    "Concurrency in modern programming languages: Rust vs Go vs Java vs Node.js vs Deno vs .NET 6 ",
    "Visual Studio Code - Tips & Tricks - Command Palette and its friends ",
    "⚠️ Don't try this at home: CSS _as_ the backend - introducing Cascading Server Sheets! ",
    " 7 Killer One-Liners in JavaScript ",
    "Top 5 state management libraries for React ",
    "50 Cool Web And Mobile Project Ideas for 2022 ",
    "Moving from JavaScript to TypeScript ",
    "Make Your Github Profile Stand Out ",
    "Latest Web Development and JavaScript Trends to Follow in 2022 ",
    "Git Cheat Sheet 📄 (50 commands + PDF and poster) ",
    "Create a whitelist for your NFT project ",
    "10 HTML and CSS Good Practices 🐅🐅 ",
    "What’s Wrong With Measuring Developer Performance (+ 10 Best Metrics) ",
    "10 ReactJS Coding Challenge (💥Coding Interview Prep💥) ",
    "5 Best Courses to learn Blockchain for Beginners in 2022 ",
];

export const queried = [
    "Production Environment ",
    "Install Gdb Mac ",
    "Laravel React",
    "Windows Terminal Customization ",
    "Ngrok Alternative ",
    "Learn Linux ",
    "Terminal for Windows",
    "How to Click Faster ",
    "Windows Keyboard on Mac ",
    "Angular State Management ",
    "Change Python Version Mac ",
    "GCC for Windows ",
    "VSCode vs VIM ",
    "Flask MongoDB ",
    "Button Animation CSS ",
    "React Chrome Extension ",
];