import img1 from "../../asset/img1.jpeg";
import img2 from "../../asset/img2.png";
import img3 from "../../asset/img3.jpeg";
import img4 from "../../asset/img4.jpeg";
import img5 from "../../asset/img5.jpg";
import img6 from "../../asset/img6.jpg";
import img7 from "../../asset/img7.jpg";
import img8 from "../../asset/img8.jpeg";
import img9 from "../../asset/img9.jpg";
import img10 from "../../asset/img10.jpeg";

export const posts = [{
        img: img1,
        date: "feb 25",
        authorName: "Daniel Gomez Jaramilo",
        postTitle: "DotVVM para studio 2022",
        postMinute: "2",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "3",
        id: "1",
    },
    {
        img: img2,
        date: "feb 25",
        authorName: "Adrianna Tacke",
        postTitle: "MongoDB $weeklyUpdate (Feb 25,2022): Joining Collections in .NET, Introducing Flexible Sync, Custom Data Enabled API, & more!",
        postMinute: "3",
        harshtags: ["Mongodb", "database", "mobile", "webdev"],
        reactions: "3",
        id: "2",
    },

    {
        img: img3,
        date: "feb 25",
        authorName: "Shaka Abara",
        postTitle: "Hallo",
        postMinute: "1",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "3",
        id: "3",
    },
    {
        img: img4,
        date: "feb 25",
        authorName: "Paulmojicatech",
        postTitle: "Install SSL on Ubuntu NGINX server",
        postMinute: "1",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "3",
        id: "4",
    },
    {
        img: img5,
        date: "feb 25",
        authorName: "Luara Fumagali",
        postTitle: "Verificando o status da instalação SQL",
        postMinute: "2",
        harshtags: [],
        reactions: "3",
        id: "5",
    },
    {
        img: img6,
        date: "feb 25",
        authorName: "David Mayer",
        postTitle: "Quiz concorsi pubblici: Guida definitiva per superare i quiz",
        postMinute: "4",
        harshtags: [],
        reactions: "3",
        id: "6",
    },
    {
        img: img7,
        date: "feb 25",
        authorName: "Johny Simpson",
        postTitle: "CSS Only Masonry Grid Layouts",
        postMinute: "3",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "11",
        id: "7",
    },
    {
        img: img8,
        date: "feb 25",
        authorName: "Angela Wilson",
        postTitle: "Prime Web Developers | PrimeWebDevelopers",
        postMinute: "2",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "3",
        id: "8",
    },
    {
        img: img9,
        date: "feb 25",
        authorName: "Ahmed Adel for Aws Comunity Builders Yu",
        postTitle: "Create your own Image CDN using AWS CloudFormation and AWS Lamda",
        postMinute: "7",
        harshtags: ["uncategorized", "agile", "event", "retrospective"],
        reactions: "2",
        id: "9",
    },
    {
        img: img10,
        date: "feb 25",
        authorName: "Nick",
        postTitle: "What's the difference between compiler, transpiler, and interpreter?",
        postMinute: "1",
        harshtags: ["programming", "Compueter"],
        reactions: "8",
        id: "10",
    },
    {
        img: img4,
        date: "feb 25",
        authorName: "Annurag",
        postTitle: "Basics of E2E Testing and Integrating Cypress with Next.js",
        postMinute: "3",
        harshtags: ["javaScript", "nextjs", "testing", "html"],
        reactions: "9",
        id: "11",
    },
    {
        img: img6,
        date: "feb 25",
        authorName: "Daniel Gomez Jaramilo",
        postTitle: "DotVVM para studio 2022",
        postMinute: "2",
        harshtags: ["webdev", "dotnet", "csharp", "html"],
        reactions: "3",
        id: "11",
    },
    {
        img: img1,
        date: "feb 25",
        authorName: "Chandreacha Sah",
        postTitle: "How Does the Magento 2 Store Locator Fulfill Your Agenda?",
        postMinute: "2",
        harshtags: ["magento", "webdev", "programming", "productivity"],
        reactions: "3",
        id: "12",
    },
    {
        img: img10,
        date: "feb 25",
        authorName: "Boostraptor",
        postTitle: "#Design a Website in Minutes with Generator - Bootstrap website builder",
        postMinute: "2",
        harshtags: [],
        reactions: "3",
        id: "12",
    },
    {
        img: img5,
        date: "feb 25",
        authorName: "PRADEEP KUMAR",
        postTitle: "WebHook integration with Stripe Payment Intents",
        postMinute: "3",
        harshtags: ["gatewaypayment", "programming", "rails", "codenewbie"],
        reactions: "44",
        id: "13",
    },
    {
        img: img7,
        date: "feb 25",
        authorName: "Nazmuz Shakib Pranto",
        postTitle: "CSSBattle | #2 Carrom",
        postMinute: "2",
        harshtags: ["challenge", "css", "cssbattle", "carom"],
        reactions: "3",
        id: "14",
    },
    {
        img: img2,
        date: "feb 25",
        authorName: "Jim Benneth for .NET ",
        postTitle: "LED Ticker Tape with .NET",
        postMinute: "5",
        harshtags: ["technology", "iot", "net", "netcore"],
        reactions: "1",
        id: "15",
    },
    {
        img: img3,
        date: "feb 25",
        authorName: "Jack Smith",
        postTitle: "For loops for beginners!",
        postMinute: "2",
        harshtags: ["javascript", "begineer"],
        reactions: "3",
        id: "16",
    },
    {
        img: img9,
        date: "feb 25",
        authorName: "SHimin Zhang",
        postTitle: "Guide your Front-End Skill Development with Bloom's Taxonomy",
        postMinute: "2",
        harshtags: ["begineers", "career", "javascript", "webdev"],
        reactions: "3",
        id: "17",
    },
    {
        img: img1,
        date: "feb 25",
        authorName: "Ahmed Hossam",
        postTitle: "100 day's challenge",
        postMinute: "1",
        harshtags: ["programming", "life", "algorithms", "productivity"],
        reactions: "5",
        id: "18",
    },
    {
        img: img3,
        date: "feb 25",
        authorName: "Md Mahir Faisal",
        postTitle: "Build a Next.js Website in 4 Steps",
        postMinute: "1",
        harshtags: [],
        reactions: "6",
        id: "19",
    },
    {
        img: img7,
        date: "feb 25",
        authorName: "Abdul-Rahman",
        postTitle: "Creating a simple PWA with Remix 💿",
        postMinute: "3",
        harshtags: ["pwa", "remix", "javascript", "npm"],
        reactions: "6",
        id: "20",
    },
    {
        img: img4,
        date: "feb 25",
        authorName: "Bernice Waweru",
        postTitle: "Maximum Subarray Sum",
        postMinute: "2",
        harshtags: ["python", "dsa", "csharp", "html"],
        reactions: "5",
        id: "21",
    },
    {
        img: img7,
        date: "feb 25",
        authorName: "Vishawk",
        postTitle: "Project 3: Build keyboard using Javascript",
        postMinute: "3",
        harshtags: ["discuss", "javascript", "html", "css"],
        reactions: "7",
        id: "22",
    },
    {
        img: img10,
        date: "feb 25",
        authorName: "ZigRazor",
        postTitle: "MTL First Beta Release",
        postMinute: "3",
        harshtags: ["showDev", "cpp", "opensource", "github"],
        reactions: "7",
        id: "23",
    },
];